SERIAL_PORT = "/dev/ttyUSB0"
SERIAL_BAUDRATE = 9600
SERIAL_TIMEOUT = 1

WELL_COUNT = 3
WELL_IDS = [1, 2, 3]
POLL_INTERVAL_SEC = 2

MQTT_BROKER = "127.0.0.1"
MQTT_PORT = 1883
MQTT_KEEPALIVE = 60

TOPIC_WATER_LEVEL = "rainwell/water_level"
TOPIC_CONTROL_CMD = "rainwell/control/cmd"
TOPIC_CONTROL_ACK = "rainwell/control/ack"

WATER_LEVEL_HIGH_THRESHOLD = 450
WATER_LEVEL_LOW_THRESHOLD = 150
